### ISSUE TITLE
No output when page loads

### ISSUE THREAD

**Issue by TheBrockEllis** [Chris-Boehm/Week-5-Game#2]
https://github.com/Chris-Boehm/Week-5-Game/blob/2660b11424d8681a45845db884196c2eb9c237db/Week%205%20Adventure%20Game.html#L33

When you first load the game, there's no data being displayed on the page. That's because you update the page on line 33 (above).

Try taking that line and putting that into a function. Then, you can call that function once when the page is done loading and then AGAIN inside of the skirmish function.

Like this:

```javascript
function updatePage() {
   text.innerHTML = "Enemy Name: " + current_enemy + "<br>" + "Current Enemy HP: " + (current_hp_enemy -= hero_dmg) + "<br>" + "Current Hero HP: " + (current_hero_hp -= current_enemy_dmg);
}

```

**Comment by Chris-Boehm** [comment]
done
