### ISSUE TITLE
Potion count as part of the person

### ISSUE THREAD

**Issue by TheBrockEllis** [Chris-Boehm/Week-5-Game#3]
https://github.com/Chris-Boehm/Week-5-Game/blob/2660b11424d8681a45845db884196c2eb9c237db/Week%205%20Adventure%20Game.html#L66

The number of potions that are available should be a part of the `player` object that you have defined in player.js. It makes sense, right? It's describing something about the player.

**Comment by Chris-Boehm** [comment]
done
